name: ${project.name}
version: ${project.version}
description: ${project.description}
main: ${project.groupId}.${project.name}
author: PureGero
website: https://github.com/JustMinecraft/${project.name}
depend: [SurvivalRanks]
api-version: 1.16